[package]
name = "system-fingerprint"
version = "0.1.0"
authors = ["Jose Miranda <jose.miranda@lexmark.com>"]
edition = "2018"

[dependencies]
partition-identity = "0.2.1"
sysinfo = "0.8.0"
sha2 = "0.8.0"
uname = "0.1.1"
